# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255, verbose_name='Date')),
                ('weight', models.IntegerField(blank=True, verbose_name='Weight')),
            ],
        ),
    ]
