# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impression',
            old_name='commnet',
            new_name='comment',
        ),
    ]
